# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
outputs:
  changes:
    description: 'The files changed by running code gen'
runs:
  using: 'docker'
  image: 'Dockerfile'
